language: python

matrix:
  include:
    - python: 3.4

before_install:
  - travis_retry wget https://bootstrap.pypa.io/get-pip.py
  - python get-pip.py
  - pip install nltk matplotlib
  - pip install codecov

script:
  - coverage run tests.py

after_success:
  - codecov